lang: es-ES
remote_theme: mmistakes/jekyll-theme-basically-basic
title: Desarrollo de Interfaces
description: Apuntes, tutoriales y actividades del módulo profesional Desarrollo de Interfaces de 2ºDAM.
author: 
  name: Fran Vargas
