lang: es-ES
remote_theme: CloudCannon/edition-jekyll-template
title: Desarrollo de Interfaces
description: Apuntes, tutoriales y actividades del módulo profesional Desarrollo de Interfaces de 2ºDAM.
author: 
  name: Fran Vargas
